### ISSUE TITLE
Vegas 15 will not load openfx-misc plugins

### ISSUE THREAD

**Issue by Dragonslayer293** [NatronGitHub/openfx-misc#73] opened 2020-05-02 19:23 UTC
Hello, I have been trying to get natron plugins to work in sony vegas for a while now, but have been unable to. Currently I have the .bundle folders in  C:\Program Files\Common Files\OFX\Plugins This is where I have some newblue and ignite plugins. In sony vegas they do not show up, but in natron they do. Do you have any way for them to work in both applications?

![Screenshot (158)](https://user-images.githubusercontent.com/18077261/80875407-9f4b6b80-8c6f-11ea-892f-ff5479c21931.png)
![Screenshot (157)](https://user-images.githubusercontent.com/18077261/80875463-a2465c00-8c6f-11ea-8485-d0e4baf124ef.png)
![Screenshot (156)](https://user-images.githubusercontent.com/18077261/80875563-aa060080-8c6f-11ea-9a70-cd065deaaba8.png)

**Comment by devernay** [comment] 2020-05-02 19:37
duplicate of #66 
please continue the discussion there.
I don't have Vegas, so I cannot debug what's wrong. Vegas has poor OpenFX support.
Are you using precompiled plugins or do you compile these yourself?

**Closed by devernay** 2020-05-02 19:37 UTC
